apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
    nodePort: 30007
  selector:
    app: go-web-app
  type: NodePort